[package]
name = "pqcrypto-mlkem"
version = "0.1.0"
edition = "2024"

[dependencies]
getrandom = "0.3"


[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }
glob = "0.3.0"
dunce = "1.0"